'use strict';
const {Router}=require('express');const {requireAuth,requireRoles}=require('../application/auth.service');const hr=require('../application/hr.service');const audit=require('../application/audit.service');
const router=Router();router.use(requireAuth,requireRoles(['ADMIN']));
// Erros esperados (com statusCode) seguem para o cliente; os inesperados são
// REGISTADOS antes de virarem 500 — sem isto um 500 do RH era invisível no log.
const run=(fn)=>(req,res)=>Promise.resolve(fn(req,res)).catch((err)=>{if(!err||!err.statusCode)console.error('[hr.router] Erro inesperado:',err);return res.status(err?.statusCode||500).json({error:err?.statusCode?err.message:'Erro interno do servidor.'});});
router.get('/stats',run(async(_q,res)=>res.json(await hr.getStats())));
router.get('/performance',run(async(_req,res)=>res.json(await hr.listPerformance())));router.post('/performance',run(async(req,res)=>res.status(201).json(await hr.createPerformance(req.body,req.user?.sub))));router.post('/performance/:id/complete',run(async(req,res)=>res.json(await hr.completePerformance(req.params.id,req.user?.sub))));
router.get('/recruitment/jobs',run(async(_req,res)=>res.json(await hr.listJobs())));router.post('/recruitment/jobs',run(async(req,res)=>res.status(201).json(await hr.createJob(req.body,req.user?.sub))));router.get('/recruitment/candidates',run(async(req,res)=>res.json(await hr.listCandidates(req.query.jobId))));router.post('/recruitment/candidates',run(async(req,res)=>res.status(201).json(await hr.createCandidate(req.body))));router.post('/recruitment/candidates/:id/stage',run(async(req,res)=>res.json(await hr.updateCandidateStage(req.params.id,req.body,req.user?.sub))));
router.get('/attendance/stats',run(async(req,res)=>res.json(await hr.getAttendanceStats(req.query.date))));router.get('/attendance',run(async(req,res)=>res.json(await hr.listAttendance({date:req.query.date,employeeId:req.query.employeeId}))));router.post('/attendance',run(async(req,res)=>res.status(201).json(await hr.recordAttendance(req.body,req.user?.sub))));
router.get('/payroll',run(async(_req,res)=>res.json(await hr.listPayroll())));router.post('/payroll',run(async(req,res)=>res.status(201).json(await hr.createPayroll(req.body.period))));router.get('/payroll/:id',run(async(req,res)=>{const p=await hr.getPayroll(req.params.id);if(!p)return res.status(404).json({error:'Folha salarial não encontrada.'});res.json(p);}));router.put('/payroll/:id/items/:employeeId',run(async(req,res)=>res.json(await hr.updatePayrollItem(req.params.id,req.params.employeeId,req.body))));router.post('/payroll/:id/status',run(async(req,res)=>{const run_=await hr.setPayrollStatus(req.params.id,req.body.status,req.user?.sub);await audit.recordFromRequest(req,{action:'hr.payroll_status',summary:`${req.user?.email??'sistema'} marcou a folha ${run_.period} como ${run_.status==='paid'?'paga':'aprovada'}`,entity_type:'hr_payroll',entity_id:run_.id,entity_label:run_.period,metadata:{status:run_.status,net_cents:Number(run_.net_cents)}});return res.json(run_);}));
router.get('/departments',run(async(_q,res)=>res.json(await hr.listDepartments())));router.post('/departments',run(async(req,res)=>res.status(201).json(await hr.createDepartment(req.body))));
router.get('/employees',run(async(req,res)=>res.json(await hr.listEmployees(req.query))));router.post('/employees',run(async(req,res)=>res.status(201).json(await hr.createEmployee(req.body))));router.get('/employees/:id',run(async(req,res)=>res.json(await hr.getEmployee(req.params.id))));router.put('/employees/:id',run(async(req,res)=>res.json(await hr.updateEmployee(req.params.id,req.body))));
router.get('/leaves',run(async(req,res)=>res.json(await hr.listLeaves(req.query))));router.post('/leaves',run(async(req,res)=>res.status(201).json(await hr.createLeave(req.body))));router.post('/leaves/:id/decision',run(async(req,res)=>{const leave=await hr.decideLeave(req.params.id,req.body,req.user?.sub);await audit.recordFromRequest(req,{action:'hr.leave_decision',summary:`${req.user?.email??'sistema'} ${leave.status==='approved'?'aprovou':'recusou'} a licença de ${leave.days} dia(s)`,entity_type:'hr_leave',entity_id:leave.id,metadata:{status:leave.status,days:leave.days,employee_id:leave.employee_id}});return res.json(leave);}));
module.exports=router;
