'use strict';
const crypto=require('crypto');const{HrOperationsRepository:repo,HrRepository}=require('../infrastructure/pg.repository');
class ValidationError extends Error{constructor(message){super(message);this.statusCode=400;}}
const tables={leaveBalances:'hr_leave_balances',shifts:'hr_shifts',timeBank:'hr_time_bank',documents:'hr_documents',checklists:'hr_checklists',trainings:'hr_trainings',benefits:'hr_benefits'};
const text=v=>typeof v==='string'?v.trim():'';const int=v=>Math.round(Number(v)||0);const day=v=>/^\d{4}-\d{2}-\d{2}$/.test(text(v))?text(v):null;
function leaveAvailable(v={}){return int(v.entitled_days)+int(v.carried_days)-int(v.used_days);}
function checklistProgress(items=[]){const safe=Array.isArray(items)?items:[];return{total:safe.length,completed:safe.filter(i=>i&&i.completed===true).length,percent:safe.length?Math.round(safe.filter(i=>i&&i.completed===true).length/safe.length*100):0};}
function timeBankBalance(entries=[]){return entries.reduce((sum,e)=>sum+(e.type==='credit'?int(e.minutes):-int(e.minutes)),0);}
async function employee(id){if(!text(id)||!await HrRepository.findEmployee(id))throw new ValidationError('Colaborador inválido.');}
async function saveLeaveBalance(dto,user){await employee(dto.employee_id);const data={id:crypto.randomUUID(),employee_id:dto.employee_id,year:int(dto.year),entitled_days:int(dto.entitled_days),carried_days:int(dto.carried_days),used_days:int(dto.used_days),created_by:user};if(data.year<2000||leaveAvailable(data)<0||Object.values(data).slice(3,6).some(v=>v<0))throw new ValidationError('Saldo de férias inválido.');return repo.upsertLeaveBalance(data);}
async function create(kind,dto,user){const table=tables[kind];if(!table)throw new ValidationError('Operação inválida.');const d={id:crypto.randomUUID(),created_by:user};if(['timeBank','documents','checklists','benefits'].includes(kind)){await employee(dto.employee_id);d.employee_id=dto.employee_id;}
 if(kind==='shifts'){if(!text(dto.name)||!/^\d{2}:\d{2}$/.test(dto.start_time)||!/^\d{2}:\d{2}$/.test(dto.end_time))throw new ValidationError('Nome e horário do turno são obrigatórios.');Object.assign(d,{name:text(dto.name),start_time:dto.start_time,end_time:dto.end_time,break_minutes:Math.max(0,int(dto.break_minutes)),work_days:Array.isArray(dto.work_days)?dto.work_days:[],active:dto.active!==false});}
 if(kind==='timeBank'){if(!day(dto.entry_date)||!['credit','debit'].includes(dto.type)||int(dto.minutes)<=0||!text(dto.reason))throw new ValidationError('Lançamento do banco de horas inválido.');Object.assign(d,{entry_date:dto.entry_date,type:dto.type,minutes:int(dto.minutes),reason:text(dto.reason)});}
 if(kind==='documents'){if(!text(dto.type)||!text(dto.title))throw new ValidationError('Tipo e título do documento são obrigatórios.');Object.assign(d,{type:text(dto.type),title:text(dto.title),reference:text(dto.reference)||null,issued_at:day(dto.issued_at),expires_at:day(dto.expires_at),status:text(dto.status)||'valid',file_url:text(dto.file_url)||null});}
 if(kind==='checklists'){if(!['onboarding','offboarding'].includes(dto.type)||!text(dto.title))throw new ValidationError('Checklist inválido.');const items=(Array.isArray(dto.items)?dto.items:[]).map((i,n)=>({id:text(i.id)||crypto.randomUUID(),label:text(i.label)||`Item ${n+1}`,completed:i.completed===true}));Object.assign(d,{type:dto.type,title:text(dto.title),due_date:day(dto.due_date),items});}
 if(kind==='trainings'){if(!text(dto.title)||!day(dto.start_date)||!['planned','in_progress','completed','cancelled'].includes(dto.status||'planned'))throw new ValidationError('Formação inválida.');Object.assign(d,{title:text(dto.title),provider:text(dto.provider)||null,start_date:dto.start_date,end_date:day(dto.end_date),status:dto.status||'planned',cost_cents:Math.max(0,int(dto.cost_cents)),participant_ids:Array.isArray(dto.participant_ids)?dto.participant_ids:[]});}
 if(kind==='benefits'){if(!['benefit','advance'].includes(dto.kind)||!text(dto.name)||int(dto.amount_cents)<0)throw new ValidationError('Benefício ou adiantamento inválido.');const amount=Math.max(0,int(dto.amount_cents)),balance=dto.kind==='advance'?int(dto.balance_cents??amount):0;if(balance<0||balance>amount)throw new ValidationError('Saldo do adiantamento inválido.');Object.assign(d,{kind:dto.kind,name:text(dto.name),amount_cents:amount,balance_cents:balance,installments:Math.max(1,int(dto.installments)||1),status:text(dto.status)||'active',start_date:day(dto.start_date),end_date:day(dto.end_date)});}
 return repo.create(table,d);}
module.exports={leaveAvailable,checklistProgress,timeBankBalance,list:k=>repo.list(tables[k]),saveLeaveBalance,create,summary:()=>repo.summary(),ValidationError};
