'use client';
import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { adminApi, HrAttendance, HrAttendanceStats, HrDepartment,HrOperationRecord, HrEmployee, HrLeave, HrPayroll, HrStats, CreateHrEmployee } from '@/services/api';
import { Button, Card, CardDescription, CardHeader, CardTitle, DataTable, Input, PageHeader, Select, StatCard } from '@/components/ui';

type Tab='overview'|'employees'|'departments'|'attendance'|'payroll'|'leaves';
const money=(c:number)=>new Intl.NumberFormat('pt-MZ',{style:'currency',currency:'MZN',maximumFractionDigits:0}).format(c/100);
const statusLabel:Record<string,string>={active:'Ativo',inactive:'Inativo',on_leave:'De licença',pending:'Pendente',approved:'Aprovado',rejected:'Recusado'};
const badge=(s:string)=>`inline-flex rounded-full border px-2.5 py-1 text-xs font-semibold ${s==='active'||s==='approved'?'border-emerald-500/20 bg-emerald-500/10 text-emerald-400':s==='pending'||s==='on_leave'?'border-amber-500/20 bg-amber-500/10 text-amber-400':'border-slate-500/20 bg-slate-500/10 text-slate-400'}`;
const emptyEmployee:CreateHrEmployee={employee_number:'',full_name:'',email:'',phone:'',tax_id:'',department_id:'',shift_id:'',job_title:'',employment_type:'permanent',hire_date:'',salary_cents:0,notes:''};

export default function HrPage(){
 const [tab,setTab]=useState<Tab>('overview'),[stats,setStats]=useState<HrStats>({total:0,active:0,on_leave:0,payroll_cents:0,pending_leaves:0});
 const today=new Date().toISOString().slice(0,10);
 const [departments,setDepartments]=useState<HrDepartment[]>([]),[shifts,setShifts]=useState<HrOperationRecord[]>([]),[employees,setEmployees]=useState<HrEmployee[]>([]),[leaves,setLeaves]=useState<HrLeave[]>([]),[attendance,setAttendance]=useState<HrAttendance[]>([]),[attendanceStats,setAttendanceStats]=useState<HrAttendanceStats>({present:0,late:0,worked_minutes:0,overtime_minutes:0});
 const [attendanceDate,setAttendanceDate]=useState(today),[attendanceForm,setAttendanceForm]=useState({employee_id:'',work_date:today,clock_in:'07:00',clock_out:'',break_minutes:60,status:'present',notes:''});
 const [payrolls,setPayrolls]=useState<HrPayroll[]>([]),[payrollPeriod,setPayrollPeriod]=useState(today.slice(0,7));
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState('');
 const [modal,setModal]=useState<'employee'|'department'|'leave'|'attendance'|null>(null),[saving,setSaving]=useState(false),[employee,setEmployee]=useState(emptyEmployee);
 const [department,setDepartment]=useState({name:'',code:'',manager_name:'',description:''}),[leave,setLeave]=useState({employee_id:'',type:'annual',start_date:'',end_date:'',reason:''});
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [s,d,e,l,a,as,p,sh]=await Promise.all([adminApi.getHrStats(),adminApi.getHrDepartments(),adminApi.getHrEmployees({pageSize:100}),adminApi.getHrLeaves(),adminApi.getHrAttendance(attendanceDate),adminApi.getHrAttendanceStats(attendanceDate),adminApi.getHrPayrolls(),adminApi.getHrOperations('shifts').catch(()=>[])]);setStats(s);setDepartments(d);setEmployees(e.items);setLeaves(l);setAttendance(a);setAttendanceStats(as);setPayrolls(p);setShifts(sh as HrOperationRecord[]);}catch(x){setError(x instanceof Error?x.message:'Não foi possível carregar o RH.');}finally{setLoading(false);}},[attendanceDate]);
 useEffect(()=>{load();},[load]);
 const visible=useMemo(()=>employees.filter(e=>(!status||e.status===status)&&(!search||`${e.full_name} ${e.employee_number} ${e.job_title}`.toLowerCase().includes(search.toLowerCase()))),[employees,search,status]);
 async function submitEmployee(ev:FormEvent){ev.preventDefault();setSaving(true);setError('');try{await adminApi.createHrEmployee(employee);setEmployee(emptyEmployee);setModal(null);await load();}catch(x){setError(x instanceof Error?x.message:'Erro ao guardar.');}finally{setSaving(false);}}
 async function submitDepartment(ev:FormEvent){ev.preventDefault();setSaving(true);try{await adminApi.createHrDepartment(department);setDepartment({name:'',code:'',manager_name:'',description:''});setModal(null);await load();}catch(x){setError(x instanceof Error?x.message:'Erro ao guardar.');}finally{setSaving(false);}}
 async function submitLeave(ev:FormEvent){ev.preventDefault();setSaving(true);try{await adminApi.createHrLeave(leave);setLeave({employee_id:'',type:'annual',start_date:'',end_date:'',reason:''});setModal(null);await load();}catch(x){setError(x instanceof Error?x.message:'Erro ao guardar.');}finally{setSaving(false);}}
 async function decide(id:string,status:'approved'|'rejected'){try{await adminApi.decideHrLeave(id,status);await load();}catch(x){setError(x instanceof Error?x.message:'Erro ao decidir.');}}
 async function submitAttendance(ev:FormEvent){ev.preventDefault();setSaving(true);try{const iso=(time:string)=>time?new Date(`${attendanceForm.work_date}T${time}:00`).toISOString():undefined;await adminApi.recordHrAttendance({...attendanceForm,clock_in:iso(attendanceForm.clock_in),clock_out:iso(attendanceForm.clock_out)});setModal(null);await load();}catch(x){setError(x instanceof Error?x.message:'Erro ao registar o ponto.');}finally{setSaving(false);}}
 async function processPayroll(){setSaving(true);try{await adminApi.createHrPayroll(payrollPeriod);await load();}catch(x){setError(x instanceof Error?x.message:'Erro ao processar a folha.');}finally{setSaving(false);}}
 async function payrollStatus(id:string,status:'approved'|'paid'){try{await adminApi.setHrPayrollStatus(id,status);await load();}catch(x){setError(x instanceof Error?x.message:'Erro ao atualizar a folha.');}}
 const employeeColumns=[{key:'employee',header:'Colaborador',cell:(e:HrEmployee)=><div><p className="font-semibold text-slate-200">{e.full_name}</p><p className="text-xs text-slate-500">{e.employee_number} · {e.email||'Sem email'}</p></div>},{key:'job',header:'Cargo e departamento',cell:(e:HrEmployee)=><div><p className="text-slate-300">{e.job_title}</p><p className="text-xs text-slate-500">{e.department_name||'Sem departamento'}</p></div>},{key:'hire',header:'Admissão',cell:(e:HrEmployee)=>new Date(`${e.hire_date}T00:00:00`).toLocaleDateString('pt-PT')},{key:'salary',header:'Salário base',cell:(e:HrEmployee)=>money(e.salary_cents)},{key:'status',header:'Estado',cell:(e:HrEmployee)=><span className={badge(e.status)}>{statusLabel[e.status]}</span>}];
 const leaveColumns=[{key:'employee',header:'Colaborador',cell:(l:HrLeave)=><div><p className="font-semibold text-slate-200">{l.employee_name}</p><p className="text-xs text-slate-500">{l.employee_number}</p></div>},{key:'type',header:'Tipo',cell:(l:HrLeave)=>l.type==='annual'?'Férias':l.type==='sick'?'Doença':l.type==='maternity'?'Maternidade/Paternidade':'Outra licença'},{key:'period',header:'Período',cell:(l:HrLeave)=><div>{new Date(`${l.start_date}T00:00:00`).toLocaleDateString('pt-PT')} — {new Date(`${l.end_date}T00:00:00`).toLocaleDateString('pt-PT')}<p className="text-xs text-slate-500">{l.days} dia(s)</p></div>},{key:'status',header:'Estado',cell:(l:HrLeave)=><span className={badge(l.status)}>{statusLabel[l.status]}</span>},{key:'actions',header:'Decisão',cell:(l:HrLeave)=>l.status==='pending'?<div className="flex gap-2"><Button size="sm" variant="primary" onClick={()=>decide(l.id,'approved')}>Aprovar</Button><Button size="sm" variant="danger" onClick={()=>decide(l.id,'rejected')}>Recusar</Button></div>:<span className="text-xs text-slate-500">Concluído</span>}];
 const attendanceColumns=[{key:'employee',header:'Colaborador',cell:(a:HrAttendance)=><div><p className="font-semibold text-slate-200">{a.employee_name}</p><p className="text-xs text-slate-500">{a.employee_number}</p></div>},{key:'in',header:'Entrada',cell:(a:HrAttendance)=>a.clock_in?new Date(a.clock_in).toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'}):'—'},{key:'out',header:'Saída',cell:(a:HrAttendance)=>a.clock_out?new Date(a.clock_out).toLocaleTimeString('pt-PT',{hour:'2-digit',minute:'2-digit'}):'Em serviço'},{key:'worked',header:'Trabalhado',cell:(a:HrAttendance)=>`${Math.floor(a.worked_minutes/60)}h ${a.worked_minutes%60}min`},{key:'late',header:'Atraso',cell:(a:HrAttendance)=><span className={a.late_minutes?'text-amber-400':'text-slate-500'}>{a.late_minutes} min</span>},{key:'extra',header:'Horas extra',cell:(a:HrAttendance)=>`${Math.floor(a.overtime_minutes/60)}h ${a.overtime_minutes%60}min`}];
 const payrollColumns=[{key:'period',header:'Período',cell:(p:HrPayroll)=><strong className="text-slate-200">{p.period}</strong>},{key:'people',header:'Colaboradores',cell:(p:HrPayroll)=>p.employee_count},{key:'gross',header:'Total bruto',cell:(p:HrPayroll)=>money(p.gross_cents)},{key:'deductions',header:'Descontos',cell:(p:HrPayroll)=>money(p.deductions_cents)},{key:'net',header:'Total líquido',cell:(p:HrPayroll)=><strong className="text-emerald-400">{money(p.net_cents)}</strong>},{key:'status',header:'Estado',cell:(p:HrPayroll)=><span className={badge(p.status)}>{p.status==='draft'?'Rascunho':p.status==='approved'?'Aprovada':'Paga'}</span>},{key:'actions',header:'Ações',cell:(p:HrPayroll)=><div className="flex gap-2">{p.status==='draft'&&<Button size="sm" variant="primary" onClick={()=>payrollStatus(p.id,'approved')}>Aprovar</Button>}{p.status==='approved'&&<Button size="sm" variant="primary" onClick={()=>payrollStatus(p.id,'paid')}>Marcar paga</Button>}</div>}];
 const tabs:[Tab,string][]=[['overview','Visão geral'],['employees','Colaboradores'],['departments','Departamentos'],['attendance','Assiduidade'],['payroll','Folha salarial'],['leaves','Férias e licenças']];
 return <div className="space-y-6 pb-10"><PageHeader title="Recursos Humanos" description="Gestão integrada de pessoas, estrutura organizacional e ausências." actions={<><Button onClick={()=>setModal('leave')}>Nova licença</Button><Button variant="primary" onClick={()=>setModal('employee')}>Novo colaborador</Button></>}/>
 {error&&<div role="alert" className="rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-300">{error}</div>}
 <div className="flex gap-1 overflow-x-auto rounded-xl border border-white/[0.06] bg-surface p-1">{tabs.map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`h-10 whitespace-nowrap rounded-lg px-4 text-sm font-semibold transition ${tab===id?'bg-brand-500 text-white':'text-slate-400 hover:bg-white/5 hover:text-slate-200'}`}>{label}</button>)}</div>
 {tab==='overview'&&<><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><StatCard label="Total de colaboradores" value={stats.total}/><StatCard label="Ativos" value={stats.active}/><StatCard label="De licença" value={stats.on_leave}/><StatCard label="Pedidos pendentes" value={stats.pending_leaves}/><StatCard label="Massa salarial mensal" value={money(stats.payroll_cents)}/></div><div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><div><CardTitle>Estrutura organizacional</CardTitle><CardDescription>Distribuição atual por departamento.</CardDescription></div><Button size="sm" onClick={()=>setModal('department')}>Novo departamento</Button></CardHeader><div className="space-y-3">{departments.length?departments.map(d=><div key={d.id} className="flex items-center justify-between rounded-xl bg-surface-elevated px-4 py-3"><div><p className="font-semibold text-slate-200">{d.name}</p><p className="text-xs text-slate-500">{d.code}{d.manager_name?` · Responsável: ${d.manager_name}`:''}</p></div><span className="text-sm font-bold text-brand-400">{d.employee_count}</span></div>):<p className="py-8 text-center text-sm text-slate-500">Crie o primeiro departamento.</p>}</div></Card><Card><CardHeader><div><CardTitle>Licenças pendentes</CardTitle><CardDescription>Pedidos que precisam de decisão.</CardDescription></div></CardHeader><div className="space-y-3">{leaves.filter(l=>l.status==='pending').slice(0,5).map(l=><div key={l.id} className="flex items-center justify-between rounded-xl bg-surface-elevated px-4 py-3"><div><p className="font-semibold text-slate-200">{l.employee_name}</p><p className="text-xs text-slate-500">{l.days} dia(s) · {l.start_date}</p></div><Button size="sm" onClick={()=>setTab('leaves')}>Analisar</Button></div>)}{!leaves.some(l=>l.status==='pending')&&<p className="py-8 text-center text-sm text-slate-500">Nenhum pedido pendente.</p>}</div></Card></div></>}
 {tab==='employees'&&<><div className="grid items-end gap-3 md:grid-cols-[1fr_220px_auto]"><Input label="Pesquisar" placeholder="Nome, número ou cargo" value={search} onChange={e=>setSearch(e.target.value)}/><Select label="Estado" value={status} onChange={e=>setStatus(e.target.value)} placeholder="Todos" options={[{value:'active',label:'Ativos'},{value:'on_leave',label:'De licença'},{value:'inactive',label:'Inativos'}]}/><Button className="h-10" variant="primary" onClick={()=>setModal('employee')}>Adicionar</Button></div><DataTable data={visible} columns={employeeColumns} getRowKey={e=>e.id} loading={loading} emptyTitle="Nenhum colaborador" emptyDescription="Cadastre a equipa ou ajuste os filtros."/></>}
 {tab==='departments'&&<><div className="flex justify-end"><Button variant="primary" onClick={()=>setModal('department')}>Novo departamento</Button></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{departments.map(d=><Card key={d.id}><div className="flex items-start justify-between"><div><span className="text-xs font-bold uppercase tracking-wider text-brand-400">{d.code}</span><h3 className="mt-1 text-lg font-bold text-slate-100">{d.name}</h3></div><span className={badge(d.status)}>{statusLabel[d.status]||d.status}</span></div><p className="mt-3 min-h-10 text-sm text-slate-500">{d.description||'Sem descrição.'}</p><div className="mt-4 flex justify-between border-t border-white/[0.06] pt-4 text-sm"><span className="text-slate-500">{d.manager_name||'Sem responsável'}</span><strong className="text-slate-200">{d.employee_count} pessoa(s)</strong></div></Card>)}</div></>}
 {tab==='attendance'&&<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Presentes" value={attendanceStats.present}/><StatCard label="Com atraso" value={attendanceStats.late}/><StatCard label="Horas trabalhadas" value={`${Math.floor(attendanceStats.worked_minutes/60)}h`}/><StatCard label="Horas extraordinárias" value={`${Math.floor(attendanceStats.overtime_minutes/60)}h`}/></div><div className="grid items-end gap-3 sm:grid-cols-[220px_auto]"><Input type="date" label="Data" value={attendanceDate} onChange={e=>setAttendanceDate(e.target.value)}/><Button className="h-10" variant="primary" onClick={()=>{setAttendanceForm({...attendanceForm,work_date:attendanceDate});setModal('attendance')}}>Registar ponto</Button></div><DataTable data={attendance} columns={attendanceColumns} getRowKey={a=>a.id} loading={loading} emptyTitle="Sem registos de assiduidade" emptyDescription="Registe a entrada dos colaboradores para esta data."/></>}
 {tab==='payroll'&&<><div className="grid items-end gap-3 sm:grid-cols-[220px_auto]"><Input type="month" label="Período salarial" value={payrollPeriod} onChange={e=>setPayrollPeriod(e.target.value)}/><Button className="h-10" variant="primary" loading={saving} onClick={processPayroll}>Processar folha</Button></div><div className="rounded-xl border border-blue-500/20 bg-blue-500/10 px-4 py-3 text-xs text-blue-300">Os descontos fiscais e previdenciários não são presumidos pelo sistema; devem ser configurados pelo RH segundo a legislação aplicável.</div><DataTable data={payrolls} columns={payrollColumns} getRowKey={p=>p.id} loading={loading} emptyTitle="Nenhuma folha salarial" emptyDescription="Selecione um período e processe a primeira folha."/></>}
 {tab==='leaves'&&<><div className="flex justify-end"><Button variant="primary" onClick={()=>setModal('leave')}>Novo pedido</Button></div><DataTable data={leaves} columns={leaveColumns} getRowKey={l=>l.id} loading={loading} emptyTitle="Nenhum pedido de licença"/></>}
 {modal&&<div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/70 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(null)}}><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-white/10 bg-surface p-6 shadow-2xl"><div className="mb-6 flex items-start justify-between"><div><h3 className="text-lg font-bold text-slate-100">{modal==='employee'?'Novo colaborador':modal==='department'?'Novo departamento':modal==='attendance'?'Registar ponto':'Novo pedido de licença'}</h3><p className="mt-1 text-xs text-slate-500">Preencha os campos obrigatórios para guardar o registo.</p></div><Button size="sm" variant="ghost" onClick={()=>setModal(null)}>Fechar</Button></div>
 {modal==='employee'&&<form onSubmit={submitEmployee} className="grid gap-4 sm:grid-cols-2"><Input required label="Número do colaborador" value={employee.employee_number} onChange={e=>setEmployee({...employee,employee_number:e.target.value})}/><Input required label="Nome completo" value={employee.full_name} onChange={e=>setEmployee({...employee,full_name:e.target.value})}/><Input type="email" label="Email" value={employee.email} onChange={e=>setEmployee({...employee,email:e.target.value})}/><Input label="Telefone" value={employee.phone} onChange={e=>setEmployee({...employee,phone:e.target.value})}/><Input label="NUIT" value={employee.tax_id} onChange={e=>setEmployee({...employee,tax_id:e.target.value})}/><Input required label="Cargo" value={employee.job_title} onChange={e=>setEmployee({...employee,job_title:e.target.value})}/><Select label="Departamento" placeholder="Sem departamento" value={employee.department_id} onChange={e=>setEmployee({...employee,department_id:e.target.value})} options={departments.map(d=>({value:d.id,label:d.name}))}/><Select label="Turno" placeholder="Turno padrão da empresa" value={employee.shift_id} onChange={e=>setEmployee({...employee,shift_id:e.target.value})} options={shifts.map(t=>({value:t.id,label:`${t.name} (${String(t.start_time).slice(0,5)}-${String(t.end_time).slice(0,5)})`}))}/><Select required label="Tipo de contrato" value={employee.employment_type} onChange={e=>setEmployee({...employee,employment_type:e.target.value as CreateHrEmployee['employment_type']})} options={[{value:'permanent',label:'Sem termo'},{value:'fixed_term',label:'Prazo determinado'},{value:'temporary',label:'Temporário'},{value:'intern',label:'Estágio'}]}/><Input required type="date" label="Data de admissão" value={employee.hire_date} onChange={e=>setEmployee({...employee,hire_date:e.target.value})}/><Input required min="0" type="number" label="Salário base (MZN)" value={employee.salary_cents/100||''} onChange={e=>setEmployee({...employee,salary_cents:Math.round(Number(e.target.value)*100)})}/><Input containerClassName="sm:col-span-2" label="Observações" value={employee.notes} onChange={e=>setEmployee({...employee,notes:e.target.value})}/><div className="flex justify-end gap-2 sm:col-span-2"><Button onClick={()=>setModal(null)}>Cancelar</Button><Button type="submit" variant="primary" loading={saving}>Guardar colaborador</Button></div></form>}
 {modal==='department'&&<form onSubmit={submitDepartment} className="grid gap-4 sm:grid-cols-2"><Input required label="Nome" value={department.name} onChange={e=>setDepartment({...department,name:e.target.value})}/><Input required label="Código" value={department.code} onChange={e=>setDepartment({...department,code:e.target.value})}/><Input label="Responsável" value={department.manager_name} onChange={e=>setDepartment({...department,manager_name:e.target.value})}/><Input label="Descrição" value={department.description} onChange={e=>setDepartment({...department,description:e.target.value})}/><div className="flex justify-end gap-2 sm:col-span-2"><Button onClick={()=>setModal(null)}>Cancelar</Button><Button type="submit" variant="primary" loading={saving}>Guardar departamento</Button></div></form>}
 {modal==='attendance'&&<form onSubmit={submitAttendance} className="grid gap-4 sm:grid-cols-2"><Select required containerClassName="sm:col-span-2" label="Colaborador" placeholder="Selecionar" value={attendanceForm.employee_id} onChange={e=>setAttendanceForm({...attendanceForm,employee_id:e.target.value})} options={employees.filter(e=>e.status==='active').map(e=>({value:e.id,label:`${e.employee_number} — ${e.full_name}`}))}/><Input required type="date" label="Data" value={attendanceForm.work_date} onChange={e=>setAttendanceForm({...attendanceForm,work_date:e.target.value})}/><Select label="Estado" value={attendanceForm.status} onChange={e=>setAttendanceForm({...attendanceForm,status:e.target.value})} options={[{value:'present',label:'Presente'},{value:'remote',label:'Trabalho remoto'},{value:'justified',label:'Ausência justificada'}]}/><Input required type="time" label="Entrada" value={attendanceForm.clock_in} onChange={e=>setAttendanceForm({...attendanceForm,clock_in:e.target.value})}/><Input type="time" label="Saída" value={attendanceForm.clock_out} onChange={e=>setAttendanceForm({...attendanceForm,clock_out:e.target.value})}/><Input min="0" type="number" label="Pausa (minutos)" value={attendanceForm.break_minutes} onChange={e=>setAttendanceForm({...attendanceForm,break_minutes:Number(e.target.value)})}/><Input label="Motivo do ajuste" value={attendanceForm.notes} onChange={e=>setAttendanceForm({...attendanceForm,notes:e.target.value})}/><div className="flex justify-end gap-2 sm:col-span-2"><Button onClick={()=>setModal(null)}>Cancelar</Button><Button type="submit" variant="primary" loading={saving}>Guardar ponto</Button></div></form>}
 {modal==='leave'&&<form onSubmit={submitLeave} className="grid gap-4 sm:grid-cols-2"><Select required containerClassName="sm:col-span-2" label="Colaborador" placeholder="Selecionar" value={leave.employee_id} onChange={e=>setLeave({...leave,employee_id:e.target.value})} options={employees.filter(e=>e.status!=='inactive').map(e=>({value:e.id,label:`${e.employee_number} — ${e.full_name}`}))}/><Select required label="Tipo" value={leave.type} onChange={e=>setLeave({...leave,type:e.target.value})} options={[{value:'annual',label:'Férias'},{value:'sick',label:'Doença'},{value:'maternity',label:'Maternidade/Paternidade'},{value:'other',label:'Outra licença'}]}/><Input required type="date" label="Data inicial" value={leave.start_date} onChange={e=>setLeave({...leave,start_date:e.target.value})}/><Input required type="date" label="Data final" value={leave.end_date} onChange={e=>setLeave({...leave,end_date:e.target.value})}/><Input label="Motivo" value={leave.reason} onChange={e=>setLeave({...leave,reason:e.target.value})}/><div className="flex justify-end gap-2 sm:col-span-2"><Button onClick={()=>setModal(null)}>Cancelar</Button><Button type="submit" variant="primary" loading={saving}>Submeter pedido</Button></div></form>}
 </div></div>}</div>;
}
